import ProtoLawCore

/// Renders a `ConformanceMap` to the `*.generated.swift` text the plugin
/// writes (PRD §5.3 sample output). Output is fully deterministic: same
/// input map → byte-identical string. The idempotence test in
/// `EmitterGoldenTests` enforces this.
///
/// Structure:
///   1. Provenance header (target name, type count, re-run command,
///      parse-failure list when any).
///   2. `import Testing` + `import ProtocolLawKit`.
///   3. Per-type `@Suite struct <TypeName>ProtocolLawTests` with
///      `@Test func <protocol>_<TypeName>()` methods, one per surviving
///      conformance after PRD §4.3 most-specific dedupe (already applied
///      by `ModuleScanner`).
///
/// Suppression markers (`// proto-law-suppress: <protocol>_<TypeName>`)
/// are honored when present in the input set — the corresponding `@Test`
/// is replaced with a comment-only stub that preserves the marker on
/// future regenerations (commit 6).
enum GeneratedFileEmitter {

    /// Stable ordering of `@Test func` methods within each emitted suite.
    /// `KnownProtocol.allCases` order matches the M1 macro's
    /// `stableOrder` so plugin-emitted and macro-emitted output sort
    /// identically when a project mixes both forms.
    private static let testEmissionOrder = KnownProtocol.allCases

    static func emit(
        target: String,
        map: ConformanceMap,
        suppressions: Set<String> = []
    ) -> String {
        var lines: [String] = []
        lines.append(contentsOf: headerLines(target: target, map: map))
        lines.append("")
        lines.append("import Testing")
        lines.append("import ProtocolLawKit")
        for entry in map.entries {
            lines.append("")
            lines.append(contentsOf: suiteLines(for: entry, suppressions: suppressions))
        }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Header

    private static func headerLines(target: String, map: ConformanceMap) -> [String] {
        var lines: [String] = []
        lines.append("// GENERATED by ProtoLawDiscoveryPlugin — DO NOT EDIT outside")
        lines.append("// `// proto-law-suppress: <protocol>_<TypeName>` markers.")
        lines.append("//")
        lines.append("// Target: \(target)")
        lines.append("// Types detected: \(map.entries.count)")
        lines.append("// Re-run: swift package protolawcheck discover --target \(target)")
        if !map.parseFailures.isEmpty {
            lines.append("//")
            lines.append("// Parse failures (\(map.parseFailures.count)):")
            for failure in map.parseFailures {
                lines.append("//   - \(failure.filePath): \(failure.message)")
            }
        }
        return lines
    }

    // MARK: - Per-type suite

    private static func suiteLines(
        for entry: ConformanceMap.Entry,
        suppressions: Set<String>
    ) -> [String] {
        var lines: [String] = []
        lines.append(provenanceComment(for: entry))
        // Skip entries whose post-filter set is empty (only iteratorProtocol
        // matched) so we don't emit empty suites.
        let emitSet = entry.conformances.filter { $0 != .iteratorProtocol }
        guard !emitSet.isEmpty else {
            lines.append("// No emit-able stdlib conformance recognized.")
            return lines
        }
        lines.append("@Suite struct \(entry.typeName)ProtocolLawTests {")
        let generatorExpr = generatorExpression(for: entry)
        let orderedConformances = testEmissionOrder.filter { emitSet.contains($0) }
        for (index, conformance) in orderedConformances.enumerated() {
            if index > 0 { lines.append("") }
            let suppressionKey = "\(conformance.testNameFragment)_\(entry.typeName)"
            if suppressions.contains(suppressionKey) {
                lines.append(contentsOf: suppressedTestLines(
                    suppressionKey: suppressionKey,
                    conformance: conformance,
                    typeName: entry.typeName
                ))
            } else {
                lines.append(contentsOf: testLines(
                    conformance: conformance,
                    typeName: entry.typeName,
                    generatorExpr: generatorExpr
                ))
            }
        }
        lines.append("}")
        return lines
    }

    /// Translate a `ConformanceMap.Entry`'s strategy to the generator
    /// expression spelled at each `using:` argument site. Mirrors the
    /// macro's `generatorExpression` (PRD §5.7) — the shared
    /// `DerivationStrategist` ensures both consumers stay aligned.
    private static func generatorExpression(for entry: ConformanceMap.Entry) -> String {
        switch entry.derivationStrategy {
        case .userGen, .todo:
            return "\(entry.typeName).gen()"
        case .caseIterable:
            return "Gen<\(entry.typeName)>.element(of: \(entry.typeName).allCases)"
        case .rawRepresentable(let rawType):
            return "\(rawType.generatorExpression)"
                + ".compactMap { \(entry.typeName)(rawValue: $0) }"
        }
    }

    private static func provenanceComment(for entry: ConformanceMap.Entry) -> String {
        let summary = entry.provenances
            .map { "\($0.filePath):\($0.line) (\($0.kind.rawValue))" }
            .joined(separator: ", ")
        return "// \(entry.typeName) — \(summary)"
    }

    // MARK: - Test method

    private static func testLines(
        conformance: KnownProtocol,
        typeName: String,
        generatorExpr: String
    ) -> [String] {
        let testName = "\(conformance.testNameFragment)_\(typeName)"
        let checkFn = conformance.checkFunctionName
        return [
            "    @Test func \(testName)() async throws {",
            "        try await \(checkFn)(",
            "            for: \(typeName).self,",
            "            using: \(generatorExpr)",
            "        )",
            "    }"
        ]
    }

    private static func suppressedTestLines(
        suppressionKey: String,
        conformance: KnownProtocol,
        typeName: String
    ) -> [String] {
        // Marker preserved verbatim; the test body is replaced with a
        // comment-only stub so the surrounding suite still compiles and
        // the marker survives the next regeneration.
        return [
            "    // proto-law-suppress: \(suppressionKey)",
            "    // (\(conformance.checkFunctionName) for \(typeName) suppressed by user marker)"
        ]
    }
}
